server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets con cache largo (Vite usa hash en el nombre)
    location ~* \.(js|css|png|jpg|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # index.html sin cache
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
